import type { Problem, PathEntry, TreeNode, MLStage } from '@/types/tree';

const STAGE_NAMES: Record<MLStage, string> = {
  problem_definition: 'Problem Definition',
  metrics: 'Metrics',
  data: 'Data',
  features: 'Features',
  model: 'Model',
  training: 'Training',
  deployment: 'Deployment',
  monitoring: 'Monitoring',
};

/**
 * Generates a markdown transcript from the path taken through the interview tree.
 *
 * @param problem - The problem definition
 * @param path - The path entries representing the user's journey
 * @param nodeMap - Map of node IDs to TreeNode objects
 * @param notes - Optional notes to append at the end of the transcript
 * @returns A formatted markdown string
 */
export function generateTranscript(
  problem: Problem,
  path: PathEntry[],
  nodeMap: Map<string, TreeNode>,
  notes?: string
): string {
  const today = new Date().toISOString().split('T')[0];

  // Build path summary from choice labels
  const pathSummary = path
    .filter((entry) => entry.choiceLabel)
    .map((entry) => entry.choiceLabel)
    .join(' → ');

  // Start building the transcript
  let transcript = `# ML System Design Interview: ${problem.title}\n\n`;
  transcript += `**Date**: ${today}\n\n`;
  transcript += `**Problem**: ${problem.description}\n\n`;
  transcript += `**Path Summary**: ${pathSummary || 'No choices made yet'}\n\n`;
  transcript += `---\n\n`;

  // Track the current stage to insert headers when it changes
  let currentStage: MLStage | null = null;

  // Process each node in the path
  for (const pathEntry of path) {
    const node = nodeMap.get(pathEntry.nodeId);
    if (!node) continue;

    // Add stage header if the stage has changed
    if (node.stage !== currentStage) {
      currentStage = node.stage;
      transcript += `## ${STAGE_NAMES[node.stage]}\n\n`;
    }

    // Determine speaker prefix
    const speakerPrefix =
      node.speaker === 'interviewer' ? '**Interviewer**' : '**Candidate**';

    // Handle different node types
    if (node.type === 'question') {
      // For question nodes, show the decision in a blockquote
      transcript += `> **Decision**: ${node.label}\n`;
      if (pathEntry.choiceLabel) {
        transcript += `> **Choice**: ${pathEntry.choiceLabel}\n\n`;
      } else {
        transcript += `>\n\n`;
      }

      // Show the interviewer's question content
      transcript += `${speakerPrefix}: ${node.content.trim()}\n\n`;

      // Show the candidate's chosen answer
      if (pathEntry.choiceIndex !== undefined && node.choices) {
        const choice = node.choices[pathEntry.choiceIndex];
        if (choice && choice.answer) {
          transcript += `**Candidate**: ${choice.answer.trim()}\n\n`;
        }
      }
    } else if (node.type === 'multi_select' && pathEntry.multiSelectValues) {
      // For multi_select nodes, show the selections
      transcript += `> **Multi-Select Decision**: ${node.label}\n`;
      const selections = pathEntry.multiSelectValues;
      const dims = node.dimensionGroups?.flatMap(g => g.dimensions) || [];
      for (const dim of dims) {
        const selectedValue = selections[dim.id];
        const selectedOption = dim.options.find(o => o.value === selectedValue);
        transcript += `> - **${dim.label}**: ${selectedOption?.label || selectedValue || 'N/A'}\n`;
      }
      transcript += `\n`;

      // Show the interviewer's prompt content
      transcript += `${speakerPrefix}: ${node.content.trim()}\n\n`;
    } else if (node.dialogue && node.dialogue.length > 0) {
      // For nodes with dialogue, render each line with speaker prefix
      for (const line of node.dialogue) {
        const lineSpeaker = line.speaker === 'interviewer' ? '**Interviewer**' : '**Candidate**';
        transcript += `${lineSpeaker}: ${line.text.trim()}\n\n`;
      }
    } else {
      // For info and terminal nodes, just show the content
      transcript += `${speakerPrefix}: ${node.content.trim()}\n\n`;
    }

    // Append citations if present
    if (node.citations && node.citations.length > 0) {
      transcript += `**Sources**:\n`;
      for (let i = 0; i < node.citations.length; i++) {
        transcript += `${i + 1}. [${node.citations[i]}](${node.citations[i]})\n`;
      }
      transcript += `\n`;
    }
  }

  // Add notes section if provided
  if (notes && notes.trim()) {
    transcript += `## Notes\n\n`;
    transcript += `${notes.trim()}\n\n`;
  }

  // Add footer
  transcript += `---\n\n`;
  transcript += `*Generated by ML System Design Interview Tool*\n`;

  return transcript;
}
