import { describe, it, expect } from 'vitest';
import { generateTranscript } from '@/components/transcript/generateTranscript';
import type { Problem, PathEntry, TreeNode } from '@/types/tree';

describe('generateTranscript', () => {
  function buildNodeMap(nodes: TreeNode[]): Map<string, TreeNode> {
    const map = new Map<string, TreeNode>();
    for (const node of nodes) {
      map.set(node.id, node);
    }
    return map;
  }

  describe('basic structure', () => {
    it('should produce minimal transcript with headers for empty path', () => {
      const problem: Problem = {
        id: 'test',
        title: 'Test Problem',
        description: 'A test problem description',
        root: 'start',
        nodes: [
          {
            id: 'start',
            stage: 'problem_definition',
            type: 'terminal',
            label: 'Start',
            speaker: 'interviewer',
            content: 'Content',
          },
        ],
      };

      const path: PathEntry[] = [];
      const nodeMap = buildNodeMap(problem.nodes);

      const transcript = generateTranscript(problem, path, nodeMap);

      expect(transcript).toContain('# ML System Design Interview: Test Problem');
      expect(transcript).toContain('**Date**:');
      expect(transcript).toContain('**Problem**: A test problem description');
      expect(transcript).toContain('**Path Summary**: No choices made yet');
      expect(transcript).toContain('---');
      expect(transcript).toContain('*Generated by ML System Design Interview Tool*');
    });
  });

  describe('speaker prefixes', () => {
    it('should show Interviewer prefix for interviewer nodes', () => {
      const problem: Problem = {
        id: 'test',
        title: 'Test',
        description: 'Test',
        root: 'start',
        nodes: [
          {
            id: 'start',
            stage: 'problem_definition',
            type: 'info',
            label: 'Start',
            speaker: 'interviewer',
            content: 'Hello from interviewer',
            next: 'end',
          },
          {
            id: 'end',
            stage: 'monitoring',
            type: 'terminal',
            label: 'End',
            speaker: 'interviewer',
            content: 'Done',
          },
        ],
      };

      const path: PathEntry[] = [{ nodeId: 'start' }];
      const nodeMap = buildNodeMap(problem.nodes);

      const transcript = generateTranscript(problem, path, nodeMap);

      expect(transcript).toContain('**Interviewer**: Hello from interviewer');
    });

    it('should show Candidate prefix for candidate nodes', () => {
      const problem: Problem = {
        id: 'test',
        title: 'Test',
        description: 'Test',
        root: 'start',
        nodes: [
          {
            id: 'start',
            stage: 'problem_definition',
            type: 'info',
            label: 'Start',
            speaker: 'candidate',
            content: 'Hello from candidate',
            next: 'end',
          },
          {
            id: 'end',
            stage: 'monitoring',
            type: 'terminal',
            label: 'End',
            speaker: 'interviewer',
            content: 'Done',
          },
        ],
      };

      const path: PathEntry[] = [{ nodeId: 'start' }];
      const nodeMap = buildNodeMap(problem.nodes);

      const transcript = generateTranscript(problem, path, nodeMap);

      expect(transcript).toContain('**Candidate**: Hello from candidate');
    });
  });

  describe('question nodes', () => {
    it('should show decision blockquote with choice label', () => {
      const problem: Problem = {
        id: 'test',
        title: 'Test',
        description: 'Test',
        root: 'q1',
        nodes: [
          {
            id: 'q1',
            stage: 'metrics',
            type: 'question',
            label: 'Choose a metric',
            speaker: 'interviewer',
            content: 'What metric would you use?',
            choices: [
              { label: 'Accuracy', answer: 'I would use accuracy', next: 'end' },
              { label: 'F1 Score', answer: 'I would use F1', next: 'end' },
            ],
          },
          {
            id: 'end',
            stage: 'monitoring',
            type: 'terminal',
            label: 'End',
            speaker: 'interviewer',
            content: 'Done',
          },
        ],
      };

      const path: PathEntry[] = [
        { nodeId: 'q1', choiceIndex: 0, choiceLabel: 'Accuracy' },
      ];
      const nodeMap = buildNodeMap(problem.nodes);

      const transcript = generateTranscript(problem, path, nodeMap);

      expect(transcript).toContain('> **Decision**: Choose a metric');
      expect(transcript).toContain('> **Choice**: Accuracy');
    });

    it('should show candidate answer for chosen option', () => {
      const problem: Problem = {
        id: 'test',
        title: 'Test',
        description: 'Test',
        root: 'q1',
        nodes: [
          {
            id: 'q1',
            stage: 'metrics',
            type: 'question',
            label: 'Choose a metric',
            speaker: 'interviewer',
            content: 'What metric would you use?',
            choices: [
              {
                label: 'Accuracy',
                answer: 'I would use accuracy because it is simple',
                next: 'end',
              },
              { label: 'F1 Score', answer: 'I would use F1', next: 'end' },
            ],
          },
          {
            id: 'end',
            stage: 'monitoring',
            type: 'terminal',
            label: 'End',
            speaker: 'interviewer',
            content: 'Done',
          },
        ],
      };

      const path: PathEntry[] = [
        { nodeId: 'q1', choiceIndex: 0, choiceLabel: 'Accuracy' },
      ];
      const nodeMap = buildNodeMap(problem.nodes);

      const transcript = generateTranscript(problem, path, nodeMap);

      expect(transcript).toContain('**Interviewer**: What metric would you use?');
      expect(transcript).toContain(
        '**Candidate**: I would use accuracy because it is simple'
      );
    });

    it('should show interviewer question content', () => {
      const problem: Problem = {
        id: 'test',
        title: 'Test',
        description: 'Test',
        root: 'q1',
        nodes: [
          {
            id: 'q1',
            stage: 'metrics',
            type: 'question',
            label: 'Question',
            speaker: 'interviewer',
            content: 'This is the question content',
            choices: [
              { label: 'A', answer: 'Answer A', next: 'end' },
              { label: 'B', answer: 'Answer B', next: 'end' },
            ],
          },
          {
            id: 'end',
            stage: 'monitoring',
            type: 'terminal',
            label: 'End',
            speaker: 'interviewer',
            content: 'Done',
          },
        ],
      };

      const path: PathEntry[] = [
        { nodeId: 'q1', choiceIndex: 1, choiceLabel: 'B' },
      ];
      const nodeMap = buildNodeMap(problem.nodes);

      const transcript = generateTranscript(problem, path, nodeMap);

      expect(transcript).toContain('**Interviewer**: This is the question content');
      expect(transcript).toContain('**Candidate**: Answer B');
    });
  });

  describe('stage headers', () => {
    it('should produce stage header when stage changes', () => {
      const problem: Problem = {
        id: 'test',
        title: 'Test',
        description: 'Test',
        root: 'start',
        nodes: [
          {
            id: 'start',
            stage: 'problem_definition',
            type: 'info',
            label: 'Start',
            speaker: 'interviewer',
            content: 'Start',
            next: 'middle',
          },
          {
            id: 'middle',
            stage: 'metrics',
            type: 'info',
            label: 'Middle',
            speaker: 'interviewer',
            content: 'Middle',
            next: 'end',
          },
          {
            id: 'end',
            stage: 'monitoring',
            type: 'terminal',
            label: 'End',
            speaker: 'interviewer',
            content: 'Done',
          },
        ],
      };

      const path: PathEntry[] = [
        { nodeId: 'start' },
        { nodeId: 'middle' },
        { nodeId: 'end' },
      ];
      const nodeMap = buildNodeMap(problem.nodes);

      const transcript = generateTranscript(problem, path, nodeMap);

      expect(transcript).toContain('## Problem Definition');
      expect(transcript).toContain('## Metrics');
      expect(transcript).toContain('## Monitoring');
    });

    it('should produce correct section headers for multiple stages in sequence', () => {
      const problem: Problem = {
        id: 'test',
        title: 'Test',
        description: 'Test',
        root: 'n1',
        nodes: [
          {
            id: 'n1',
            stage: 'problem_definition',
            type: 'info',
            label: 'N1',
            speaker: 'interviewer',
            content: 'Content 1',
            next: 'n2',
          },
          {
            id: 'n2',
            stage: 'data',
            type: 'info',
            label: 'N2',
            speaker: 'interviewer',
            content: 'Content 2',
            next: 'n3',
          },
          {
            id: 'n3',
            stage: 'features',
            type: 'info',
            label: 'N3',
            speaker: 'interviewer',
            content: 'Content 3',
            next: 'n4',
          },
          {
            id: 'n4',
            stage: 'model',
            type: 'terminal',
            label: 'N4',
            speaker: 'interviewer',
            content: 'Content 4',
          },
        ],
      };

      const path: PathEntry[] = [
        { nodeId: 'n1' },
        { nodeId: 'n2' },
        { nodeId: 'n3' },
        { nodeId: 'n4' },
      ];
      const nodeMap = buildNodeMap(problem.nodes);

      const transcript = generateTranscript(problem, path, nodeMap);

      expect(transcript).toContain('## Problem Definition');
      expect(transcript).toContain('## Data');
      expect(transcript).toContain('## Features');
      expect(transcript).toContain('## Model');
    });

    it('should not repeat stage header if stage stays the same', () => {
      const problem: Problem = {
        id: 'test',
        title: 'Test',
        description: 'Test',
        root: 'start',
        nodes: [
          {
            id: 'start',
            stage: 'problem_definition',
            type: 'info',
            label: 'Start',
            speaker: 'interviewer',
            content: 'Start',
            next: 'middle',
          },
          {
            id: 'middle',
            stage: 'problem_definition',
            type: 'info',
            label: 'Middle',
            speaker: 'interviewer',
            content: 'Middle',
            next: 'end',
          },
          {
            id: 'end',
            stage: 'monitoring',
            type: 'terminal',
            label: 'End',
            speaker: 'interviewer',
            content: 'Done',
          },
        ],
      };

      const path: PathEntry[] = [
        { nodeId: 'start' },
        { nodeId: 'middle' },
      ];
      const nodeMap = buildNodeMap(problem.nodes);

      const transcript = generateTranscript(problem, path, nodeMap);

      // Should only appear once
      const matches = transcript.match(/## Problem Definition/g);
      expect(matches?.length).toBe(1);
    });
  });

  describe('path summary', () => {
    it('should list choice labels joined by arrow', () => {
      const problem: Problem = {
        id: 'test',
        title: 'Test',
        description: 'Test',
        root: 'q1',
        nodes: [
          {
            id: 'q1',
            stage: 'metrics',
            type: 'question',
            label: 'Question 1',
            speaker: 'interviewer',
            content: 'Pick one',
            choices: [
              { label: 'Choice A', answer: 'Answer A', next: 'q2' },
              { label: 'Choice B', answer: 'Answer B', next: 'q2' },
            ],
          },
          {
            id: 'q2',
            stage: 'data',
            type: 'question',
            label: 'Question 2',
            speaker: 'interviewer',
            content: 'Pick another',
            choices: [
              { label: 'Choice X', answer: 'Answer X', next: 'end' },
              { label: 'Choice Y', answer: 'Answer Y', next: 'end' },
            ],
          },
          {
            id: 'end',
            stage: 'monitoring',
            type: 'terminal',
            label: 'End',
            speaker: 'interviewer',
            content: 'Done',
          },
        ],
      };

      const path: PathEntry[] = [
        { nodeId: 'q1', choiceIndex: 0, choiceLabel: 'Choice A' },
        { nodeId: 'q2', choiceIndex: 1, choiceLabel: 'Choice Y' },
        { nodeId: 'end' },
      ];
      const nodeMap = buildNodeMap(problem.nodes);

      const transcript = generateTranscript(problem, path, nodeMap);

      expect(transcript).toContain('**Path Summary**: Choice A → Choice Y');
    });
  });

  describe('terminal nodes', () => {
    it('should include terminal node content', () => {
      const problem: Problem = {
        id: 'test',
        title: 'Test',
        description: 'Test',
        root: 'start',
        nodes: [
          {
            id: 'start',
            stage: 'problem_definition',
            type: 'info',
            label: 'Start',
            speaker: 'interviewer',
            content: 'Start',
            next: 'end',
          },
          {
            id: 'end',
            stage: 'monitoring',
            type: 'terminal',
            label: 'End',
            speaker: 'interviewer',
            content: 'This is the terminal content',
          },
        ],
      };

      const path: PathEntry[] = [{ nodeId: 'start' }, { nodeId: 'end' }];
      const nodeMap = buildNodeMap(problem.nodes);

      const transcript = generateTranscript(problem, path, nodeMap);

      expect(transcript).toContain('**Interviewer**: This is the terminal content');
    });
  });

  describe('content formatting', () => {
    it('should trim content of trailing whitespace', () => {
      const problem: Problem = {
        id: 'test',
        title: 'Test',
        description: 'Test',
        root: 'start',
        nodes: [
          {
            id: 'start',
            stage: 'problem_definition',
            type: 'terminal',
            label: 'Start',
            speaker: 'interviewer',
            content: 'Content with trailing spaces   \n\n',
          },
        ],
      };

      const path: PathEntry[] = [{ nodeId: 'start' }];
      const nodeMap = buildNodeMap(problem.nodes);

      const transcript = generateTranscript(problem, path, nodeMap);

      expect(transcript).toContain(
        '**Interviewer**: Content with trailing spaces'
      );
      expect(transcript).not.toContain('Content with trailing spaces   \n\n');
    });
  });

  describe('dialogue nodes', () => {
    it('should render dialogue lines with speaker prefixes when dialogue is present', () => {
      const problem: Problem = {
        id: 'test',
        title: 'Test',
        description: 'Test',
        root: 'start',
        nodes: [
          {
            id: 'start',
            stage: 'problem_definition',
            type: 'info',
            label: 'Start',
            speaker: 'interviewer',
            content: 'Flat content fallback',
            next: 'end',
            dialogue: [
              { speaker: 'interviewer', text: 'Welcome to the interview!' },
              { speaker: 'candidate', text: 'Thanks, excited to be here.' },
            ],
          },
          {
            id: 'end',
            stage: 'monitoring',
            type: 'terminal',
            label: 'End',
            speaker: 'interviewer',
            content: 'Done',
          },
        ],
      };

      const path: PathEntry[] = [{ nodeId: 'start' }];
      const nodeMap = buildNodeMap(problem.nodes);

      const transcript = generateTranscript(problem, path, nodeMap);

      expect(transcript).toContain('**Interviewer**: Welcome to the interview!');
      expect(transcript).toContain('**Candidate**: Thanks, excited to be here.');
      // Should NOT contain the flat content when dialogue is present
      expect(transcript).not.toContain('Flat content fallback');
    });

    it('should use flat content when dialogue is not present', () => {
      const problem: Problem = {
        id: 'test',
        title: 'Test',
        description: 'Test',
        root: 'start',
        nodes: [
          {
            id: 'start',
            stage: 'problem_definition',
            type: 'info',
            label: 'Start',
            speaker: 'interviewer',
            content: 'This is flat content',
            next: 'end',
          },
          {
            id: 'end',
            stage: 'monitoring',
            type: 'terminal',
            label: 'End',
            speaker: 'interviewer',
            content: 'Done',
          },
        ],
      };

      const path: PathEntry[] = [{ nodeId: 'start' }];
      const nodeMap = buildNodeMap(problem.nodes);

      const transcript = generateTranscript(problem, path, nodeMap);

      expect(transcript).toContain('**Interviewer**: This is flat content');
    });

    it('should use flat content when dialogue array is empty', () => {
      const problem: Problem = {
        id: 'test',
        title: 'Test',
        description: 'Test',
        root: 'start',
        nodes: [
          {
            id: 'start',
            stage: 'problem_definition',
            type: 'terminal',
            label: 'Start',
            speaker: 'interviewer',
            content: 'Flat content used',
            dialogue: [],
          },
        ],
      };

      const path: PathEntry[] = [{ nodeId: 'start' }];
      const nodeMap = buildNodeMap(problem.nodes);

      const transcript = generateTranscript(problem, path, nodeMap);

      expect(transcript).toContain('**Interviewer**: Flat content used');
    });
  });

  describe('complex paths', () => {
    it('should generate correct transcript for complete interview path', () => {
      const problem: Problem = {
        id: 'test',
        title: 'Flight Delay Prediction',
        description: 'Predict flight delays',
        root: 'start',
        nodes: [
          {
            id: 'start',
            stage: 'problem_definition',
            type: 'info',
            label: 'Problem Introduction',
            speaker: 'interviewer',
            content: 'Let us design a flight delay prediction system.',
            next: 'q1',
          },
          {
            id: 'q1',
            stage: 'metrics',
            type: 'question',
            label: 'Choose Metric',
            speaker: 'interviewer',
            content: 'What metric should we optimize for?',
            choices: [
              {
                label: 'Precision',
                answer: 'I would focus on precision to minimize false alarms.',
                next: 'end',
              },
              {
                label: 'Recall',
                answer: 'I would focus on recall to catch all delays.',
                next: 'end',
              },
            ],
          },
          {
            id: 'end',
            stage: 'monitoring',
            type: 'terminal',
            label: 'Conclusion',
            speaker: 'interviewer',
            content: 'Great job! Interview complete.',
          },
        ],
      };

      const path: PathEntry[] = [
        { nodeId: 'start' },
        { nodeId: 'q1', choiceIndex: 1, choiceLabel: 'Recall' },
        { nodeId: 'end' },
      ];
      const nodeMap = buildNodeMap(problem.nodes);

      const transcript = generateTranscript(problem, path, nodeMap);

      expect(transcript).toContain('# ML System Design Interview: Flight Delay Prediction');
      expect(transcript).toContain('**Problem**: Predict flight delays');
      expect(transcript).toContain('**Path Summary**: Recall');
      expect(transcript).toContain('## Problem Definition');
      expect(transcript).toContain(
        '**Interviewer**: Let us design a flight delay prediction system.'
      );
      expect(transcript).toContain('## Metrics');
      expect(transcript).toContain('> **Decision**: Choose Metric');
      expect(transcript).toContain('> **Choice**: Recall');
      expect(transcript).toContain(
        '**Interviewer**: What metric should we optimize for?'
      );
      expect(transcript).toContain(
        '**Candidate**: I would focus on recall to catch all delays.'
      );
      expect(transcript).toContain('## Monitoring');
      expect(transcript).toContain('**Interviewer**: Great job! Interview complete.');
    });
  });
});
